### ISSUE TITLE
日志链接

### ISSUE THREAD

**Issue by SKTT1Ryze** [SKTT1Ryze/xv6-k210#1]
**该 issure 用于记录同学们的日志链接，方便大家学习交流。**

**Comment by SKTT1Ryze** [comment]
https://github.com/SKTT1Ryze/Daily_Of_CCC#day-72-20201018

**Comment by retrhelo** [comment]
https://my.oschina.net/u/4528547
目前还没什么东西，学到什么的话会往上面写的

**Comment by YongkangLi** [comment]
https://github.com/YongkangLi/log

**Comment by AtomHeartCoder** [comment]
https://github.com/AtomHeartCoder/Diary

**Comment by love-lee1993** [comment]
https://github.com/love-lee1993/Log

**Comment by SKTT1Ryze** [comment]
close this issue.
