### ISSUE TITLE
how to launch shell process？

### ISSUE THREAD

**Issue by pzzpl** [SKTT1Ryze/xv6-k210#15]
目前能够启动一个用户进程。但是我想把终端进程启动起来，要做些什么吗？

**Comment by SKTT1Ryze** [comment]
目前这个项目还不完善，文件系统部分还没移植完成。  
如果您想要跑 shell 的话，需要先把文件系统移植好，然后在文件系统里面放用户程序，在用户程序里面实现 shell。  
总之十分抱歉，目前这个项目本身还不能运行终端进程，需要进一步的工作。

**Comment by SKTT1Ryze** [comment]
close this issue
