### ISSUE TITLE
请教 k210 接收键盘输入出错

### ISSUE THREAD

**Issue by wjsgtxy** [SKTT1Ryze/xv6-k210#16]
你好，小白用户请教一个问题。我在虚拟机中用Ubuntu18连接了k210开发版, 运行了make run命令，可以一直显示tick的输出，但是之后我按一下键盘，会报错而且不能回显按键，我在你项目 img/ s_extern_interrupt.png 最下面看到你的是可以显示键盘输出的 ：“received ***”。 想问这个是什么原因，该如何处理呢？感谢！
![error2](https://user-images.githubusercontent.com/20908137/104118776-66b77200-5366-11eb-8302-899b85d78c79.png)

**Comment by wjsgtxy** [comment]
不知道能不能看到上传的图片，它错误输出为：
 [rustsbi] panicked at 'unhandled trap! mcause: Exception(StoreFault), mepc: 00000000800014d8, mtval: 000000008001bd00', src/main.rs:510:18

**Comment by SKTT1Ryze** [comment]
您好，是这样的，键盘输入属于外部中断，我们移植外部中断的时候借助了一个东西叫 rustsbi，这个东西帮助我们获取键盘输入。  
但是最近这个 rustsbi 的实现修改了，因此键盘输入的处理出了点小问题。再由于我们目前还不需要键盘输入，因此就没来得及修这个 bug。谢谢您的提醒，我们会尽早把这个bug修复

**Comment by SKTT1Ryze** [comment]
另外我看到您的输出里面 sd 卡初始化失败了，建议检查您开发板上的 sd 卡是否插好

**Comment by wjsgtxy** [comment]
> 您好，是这样的，键盘输入属于外部中断，我们移植外部中断的时候借助了一个东西叫 rustsbi，这个东西帮助我们获取键盘输入。
> 但是最近这个 rustsbi 的实现修改了，因此键盘输入的处理出了点小问题。再由于我们目前还不需要键盘输入，因此就没来得及修这个 bug。谢谢您的提醒，我们会尽早把这个bug修复

看到您更新的rustsbi代码了，刚试了下已经可以了，非常感谢！

**Comment by SKTT1Ryze** [comment]
啊这，我这还没可以呢？

**Comment by XiangyuSu611** [comment]
我这里更新一下 rustsbi 代码也可以了

**Comment by SKTT1Ryze** [comment]
@XiangyuSu611 @wjsgtxy 能否请两位打包一下代码（zip 或 tar）发我邮箱一份？非常感谢QAQ。  
邮箱地址：1276675421@qq.com

**Comment by SKTT1Ryze** [comment]
谢谢两位热心同学的帮助 @wjsgtxy @XiangyuSu611 我找到问题所在了。  
两个如果后面还有什么问题，也欢迎在此 repo 的 issue 上提出来，我们看到之后会第一时间回复。

**Comment by SKTT1Ryze** [comment]
close this issue
