### ISSUE TITLE
关于shell实现的问题

### ISSUE THREAD

**Issue by herical** [SKTT1Ryze/xv6-k210#17]
你好，我们在您的xv6-user中看到了shell的实现，请问该怎么启动这些shell

**Comment by SKTT1Ryze** [comment]
您好，因为我们的移植进度由于各位同学的学业而停滞了，文件系统还没移植完成，所以现在还不支持启动 shell。  
现在我们的用户进程是写死在内核里面的，会打印一些字符。  
我们目前正在抓紧文件系统的移植，大概 2 月之前可以完成，到时候可以留意一下我们的项目，谢谢。

**Comment by herical** [comment]
好的，谢谢您的回复



---原始邮件---
发件人: "hustccc"<notifications@github.com&gt;
发送时间: 2021年1月12日(周二) 晚上10:08
收件人: "SKTT1Ryze/xv6-k210"<xv6-k210@noreply.github.com&gt;;
抄送: "herical"<1027688429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [SKTT1Ryze/xv6-k210] 关于shell实现的问题 (#17)




 
您好，因为我们的移植进度由于各位同学的学业而停滞了，文件系统还没移植完成，所以现在还不支持启动 shell。
 现在我们的用户进程是写死在内核里面的，会打印一些字符。
 我们目前正在抓紧文件系统的移植，大概 2 月之前可以完成，到时候可以留意一下我们的项目，谢谢。

**Comment by SKTT1Ryze** [comment]
close this issue
