### ISSUE TITLE
关于双核启动进程调度的问题

### ISSUE THREAD

**Issue by XiangyuSu611** [SKTT1Ryze/xv6-k210#18]
您好，我在使用双核模式运行代码时，初始化了8个测试进程观察双核内的进程调度，出现两个问题：1. 调度不会按照进程的pid顺序进行（该问题在单核上也会出现），2.双核只有一个核心会出现进程调度行为。以下是我的截图。请问是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/34934357/104557058-8e1a8180-567b-11eb-9d6c-0903670495c1.png)
![image](https://user-images.githubusercontent.com/34934357/104557084-9a9eda00-567b-11eb-80c0-33c35e488dc0.png)
谢谢！

**Comment by SKTT1Ryze** [comment]
非常感谢您的问题，指出了我们项目的问题所在。  
首先第一个问题，我觉得这里进程调度不按 pid 的顺序执行是正常的，这里的 pid 不是严格意义上的进程标识符，按照何种顺序调度由内核实现决定。而我们在移植过程中并没有太过注意这个细节，您如果感兴趣这里的原因的话可以去看下源码实现。  
第二个问题，这是我们项目的一个 bug，因为我们没在第 1 个核（区别于第 0 个）里面设置时钟中断，即 `timerinit()` 这个函数，因此第 1 个核一直没有进入时钟中断处理函数里面。而进程切换就是在时钟中断里面做的，所以第 1 个核一直没有进程调度。  
非常感谢您帮我们发现了这个bug，现在这个 bug 已经被我修好并且更新到 github 的代码中去了，您可以 `git pull` 更新代码再尝试一下。

**Comment by XiangyuSu611** [comment]
已经可以观察到双核调度了，非常感谢！
