### ISSUE TITLE
关于xv6实验"Lab: System calls"中的一点问题

### ISSUE THREAD

**Issue by retrhelo** [SKTT1Ryze/xv6-k210#3]
[https://pdos.csail.mit.edu/6.828/2020/labs/syscall.html](https://pdos.csail.mit.edu/6.828/2020/labs/syscall.html)
关于其中的第二个实验"Sysinfo"，在实现`struct sysinfo`赋值的代码中为什么一定要使用`copyout()`函数来实现？用户代码调用`sysinfo()`的syscall时不是已经将一个struct sysinfo指针作为参数传入了吗？为什么这里不能像普通的C语言代码那样简单地使用这个传入的指针进行赋值？

`copyout()`函数的原型为`int copyout(pagetable_t pagetable, uint64 dstva, char *src, uint64 len)`，从参数名来看似乎是使用到了虚拟地址。是说因为用户态传入的`struct sysinfo`指针使用的是虚拟地址所以无法直接在内核中访问吗？

**Comment by YongkangLi** [comment]
System calls are running in the kernel space(using kernel pagetable). You have to copy the result to the user space(using process pagetable). These are different. (If I remembered correctly and understood you issue)

**Comment by SKTT1Ryze** [comment]
我目前还没做过 xv6 实验，在这方面没有太大发言权。wqy 同学好像已经做完了 xv6 的实验，你可以询问一下他。但我觉得 xv6 的实验灵活性还是挺高的，你可以用你自己的方式实现一下，然后看看结果是不是正确。  
然后关于在内核中访问虚拟地址，因为内核的内存空间也是经过了页表转换的，只不过在 xv6 中内核空间是直接映射，但我们一般访问的都是虚拟地址。

**Comment by retrhelo** [comment]
嗯嗯，今天分析了一下代码感觉应该是内核态和用户态pagetable的区别

**Comment by colinaaa** [comment]
[这本书](https://github.com/mit-pdos/xv6-riscv-book)上好像有讲为什么，实验三的目的就是在内核中直接访问用户态虚拟地址

**Comment by SKTT1Ryze** [comment]
close this issue.
