### ISSUE TITLE
关于xv6中的per-process pagetable以及寄存器satp

### ISSUE THREAD

**Issue by retrhelo** [SKTT1Ryze/xv6-k210#4]
最近在看以及在做lab3（也就是pagetable）相关的内容了。其中有一点我不是很明白。xv6会给每一个process分配一个pagetable放在PCB（`struct proc`）中，那么操作系统切进程的时候是会将PCB中的pagetable载入到satp中吗？否则我实在是想不通如何将虚拟地址映射到一块与进程有关的物理地址上去。riscv-book中貌似没有专门讲到这个问题。

**Comment by SKTT1Ryze** [comment]
xv6 里面没有内核进程的概念（至少我没看到内核进程），它的进程全部是用户进程，而对于用户来说是页表和虚拟内存管理这部分是透明的，用户只能看到虚拟地址。  
而我们知道用户程序是跑在 OS 上的，OS 为用户程序提供服务，这种服务就是系统调用。用户程序使用 OS 提供的系统调用来实现他们的功能。  
因此用户程序里面的地址，对于 OS 来说就是虚拟地址，虚拟地址到物理地址的转换，是在系统调用里面。

**Comment by SKTT1Ryze** [comment]
比如说`fork`系统调用：  
```C
// Create a new process, copying the parent.
// Sets up child kernel stack to return as if from fork() system call.
int
fork(void)
{
...
// Copy user memory from parent to child.
  if(uvmcopy(p->pagetable, np->pagetable, p->sz) < 0){
    freeproc(np);
    release(&np->lock);
    return -1;
  }
...
}
这里的实现是会用到页表来作为参数的，因此我觉得是系统调用的实现中会将用户进程的页表作为参数进行传递，间接达到地址转换的效果
```

**Comment by SKTT1Ryze** [comment]
我没有很细致看过系统调用代码，但我猜是这样子的，如果有错欢迎指正。

**Comment by retrhelo** [comment]
当用户代码通过syscall进入内核代码时（以及从内核代码中出来时）会修改satp以及清空TLB，在trampoline.S中的uservec()以及userret()函数中有这样的指令
```
# 以uservec()为例，约是trampoline.S第78行的位置
csrw satp, t1
sfence.vma zero, zero
```

**Comment by SKTT1Ryze** [comment]
嗯，好像是这样子的。

**Comment by SKTT1Ryze** [comment]
close this issue.
