### ISSUE TITLE
userinit()无法通过

### ISSUE THREAD

**Issue by retrhelo** [SKTT1Ryze/xv6-k210#5]
试着编译并跑了一下代码，发现每次都会在`userinit()`（main.c: 38)处panic。再进一步地追下去，发现是`userinit()`最后的`release()`失败了。似乎是代码中的某处修改了cpu->noff，导致无法正常地解锁。各位有什么头绪吗？（苦笑）

**Comment by retrhelo** [comment]
和邵老师交流了一下，目前初步怀疑是某些汇编指令（spinlock.c: 33）的行为在K210上可能和预期的不一致，现在正在做这方面的检查

**Comment by SKTT1Ryze** [comment]
如果 panic 了就试着按 k210 上的复位键，多试几次。现在 xv6 内核还没完全移植好，是会有 bug 的。

**Comment by retrhelo** [comment]
是的，这个bug似乎是有一定几率触发的。话说关于k210有相关的指令手册之类的东西吗？因为这个bug太诡异了，我觉得邵老师说得在理，我也觉得可能是原本xv6用到的那几条原子操作语句在k210上的行为和我们设想的不一样。如果有手册之类的东西能查一查就太好了

**Comment by SKTT1Ryze** [comment]
k210 没有文档，现在 k210 很多东西都是洛佳当年逆向出来的

**Comment by retrhelo** [comment]
好吧，那就很痛脑袋了。那我明天问问洛佳吧，说不定这个问题就有答案了

**Comment by retrhelo** [comment]
今天又分析了一下昨天出问题的代码，今天大概是找到问题所在了。xv6里面使用的spinlock需要用到`tp`寄存器来区分不同的CPU（kernel/proc.c: cpuid()），而在代码中没有对应的用于初始化`tp`寄存器的代码。我试着在main()中加入了一句`asm volatile("mv tp, %0" : : "r" (hartid & 0x1));`后问题似乎就解决了。

**Comment by SKTT1Ryze** [comment]
可以提交一下 pr 我看看

**Comment by SKTT1Ryze** [comment]
close this issue.
