### ISSUE TITLE
关于sdcard_test()中一个可能的bug

### ISSUE THREAD

**Issue by retrhelo** [SKTT1Ryze/xv6-k210#9]
刚刚检查了一下sdcard_test()中相关的操作，发现sdcard_test()(src/sdcard.c)中存在一个可能的bug。代码中大量的使用`sizeof(buffer)`和`sizeof(pre_buffer)`来表示buffer和pre_buffer数据区的长度。这两个数据区的长度理论上应该是4096B(4KB)，但是如果使用sizeof运算符的话，得到的结果则应该是**指针的长度**。因为`buffer`和`pre_buffer`都是`uint8*`类型的，使用sizeof运算符得到的应该是它们的类型的长度，而非所期望的4KB。

**Comment by SKTT1Ryze** [comment]
这个的确有点问题，你可以修改一下代码提交一个 pull request 来修改这个错误。

**Comment by retrhelo** [comment]
On Tue, 15 Dec 2020 06:51:58 -0800
hustccc <notifications@github.com> wrote:

> 这个的确有点问题，你可以修改一下代码提交一个 pull request
> 来修改这个错误。
> 

嗯嗯好，这个我到时候和文件系统的修改一起交上来吧

**Comment by AtomHeartCoder** [comment]
跑`sdcard_init()`的时候`SD_CMD8`出错了。之前 @retrhelo 也遇到过这个问题，我们手头的maix bit板子一直不能成功初始化sd卡。

**Comment by SKTT1Ryze** [comment]
尝试换个 sd 卡，我也遇到过类似的问题，但换张 sd 卡就好了，这个可能和 sd 卡有关

**Comment by SKTT1Ryze** [comment]
如果换张 sd 卡也不行的话就去找王清雨拿他手上的那个 maix docx 板子试一下

**Comment by SKTT1Ryze** [comment]
close this issue.
